#pragma once


#define DRAG_DROP_CONTENT_BROWSER_MESH                  "CONTENT_BROWSER_MESH"
#define DRAG_DROP_CONTENT_BROWSER_TEXTURE               "CONTENT_BROWSER_TEXTURE"
#define DRAG_DROP_CONTENT_BROWSER_MATERIAL              "CONTENT_BROWSER_MATERIAL"
#define DRAG_DROP_CONTENT_BROWSER_MATERIAL_INST         "CONTENT_BROWSER_MATERIAL_INST"
#define DRAG_DROP_CONTENT_BROWSER_WORLD                 "CONTENT_BROWSER_WORLD"
#define DRAG_DROP_CONTENT_BROWSER_MULTI                 "CONTENT_BROWSER_MULTI"
